### ISSUE TITLE
Cross compatibility between Pytorch native versions and Pytorch engines/apis

### ISSUE THREAD

**Issue by carlosuc3m** [awslabs/djl#544]
## Question
Hello there,
I was wondering if there exists a document secifying the cross compatibility between Pytorch native versions and Pytorch engines/apis. I have not been able to found anything and in order to find it out I have been doing it by trial and error.
Thank you for your time,
Carlos

**Comment by zachgk** [comment]
You can take a look at the PyTorch engine README document: https://github.com/awslabs/djl/blob/master/pytorch/pytorch-engine/README.md. There is only a single PyTorch version that matches each version of DJL. If you view this page at a version tag rather than the master branch, you can see what versions are supported by the various released versions of DJL.

**Comment by frankfliu** [comment]
@carlosuc3m 
The recommended way is to use DJL's bom to manage your dependencies: http://docs.djl.ai/bom/index.html
You can find the bom pom.xml file from maven central for each version: https://search.maven.org/artifact/ai.djl/bom/0.9.0/pom

**Comment by lanking520** [comment]
@carlosuc3m Close this issue for now. If you have any more concerns about the versioning issue, please feel free to reopen!
