### ISSUE TITLE
not found Symbol.json after save model 

### ISSUE THREAD

**Issue by yanchaoguo** [awslabs/djl#97]
使用transfer_learning将训练好的model进行保存，生成的文件不包含Symbol 和 synset 那么load时会报Symbol file not found in:

**Comment by yanchaoguo** [comment]
@frankfliu can you help me

**Comment by frankfliu** [comment]
Transfer learning example saved models is DJL model format. Since you changed the Blocks, it's consider as an imperative model. it doesn't require symbol file.

When you load the model, you have to call setBlock() to set the modified block first.
Here is example how to load an imperative mode: https://github.com/awslabs/djl/blob/master/model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/classification/ResNetModelLoader.java#L142-L144

For the synset file, you have manually load it. You can set how you want to load synset when you build your translator: https://github.com/awslabs/djl/blob/master/api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java#L123-L148

**Comment by yanchaoguo** [comment]
> Transfer learning example saved models is DJL model format. Since you changed the Blocks, it's consider as an imperative model. it doesn't require symbol file.
> 
> When you load the model, you have to call setBlock() to set the modified block first.
> Here is example how to load an imperative mode: https://github.com/awslabs/djl/blob/master/model-zoo/src/main/java/ai/djl/basicmodelzoo/cv/classification/ResNetModelLoader.java#L142-L144
> 
> For the synset file, you have manually load it. You can set how you want to load synset when you build your translator: https://github.com/awslabs/djl/blob/master/api/src/main/java/ai/djl/modality/cv/translator/BaseImageTranslator.java#L123-L148
> 
> We don't support export Model in native engine format today. We are consider adding this feature in future.

thank you for my help I will try it
